version: 2
updates:
  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
      
  # Dev container environment
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "infrastructure"
    open-pull-requests-limit: 3
        
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "python"
    versioning-strategy: "lockfile-only"
    open-pull-requests-limit: 5