# Debug configuration
debug:
  # General debug settings
  debug_mode: false
  profile_mode: none  # none, time, memory, cpu, scalene
  debug_level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  debug_output: /tmp/debug/python-slim-debug.log
  
  # Debugpy settings
  debugpy_enable: false
  debugpy_wait: false
  debugpy_host: 0.0.0.0
  debugpy_port: 5678
  
  # Profile settings
  profiles_dir: /tmp/profiles