services:
  app:
    env_file:
      - .env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - USER_UID=1000
        - USER_GID=1000
        - DEV_MODE=${DEV_MODE:-true}
    storage_opt:
      size: ${STORAGE:-15G}
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    healthcheck:
      test: [ "CMD", "id", "vscode" ]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    env_file:
      - .env
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5000:5000"
      - "5432:5432"
      - "8000:8000"
      - "3000:3000"
      - "6379:6379"
      - "8080:8080"
      - "9000:9000"
      - "4000:4000"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?Database user must be specified}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Database password must be specified}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
