version: "3.8"

services:
  python-builder:
    image: python-slim-builder:latest
    build:
      context: ../..
      dockerfile: .devcontainer/container/Dockerfile.build
      args:
        BUILDKIT_INLINE_CACHE: ${BUILD_BUILDKIT_INLINE_CACHE:-1}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.12}
        CCACHE_DIR: ${CCACHE_DIR_ABSOLUTE:-/.ccache}
        CCACHE_MAXSIZE: 5G
        CMAKE_BUILD_PARALLEL_LEVEL: ${HOST_CPUS:-4}
      cache_from:
        - python-slim-builder:latest
    volumes:
      - python-ccache-volume:${CCACHE_DIR_ABSOLUTE:-/.ccache}
      - python-pip-cache:/root/.cache/pip

  python-dev:
    container_name: ${COMPOSE_PROJECT_NAME:-python-slim-dev}
    build:
      context: ../..
      dockerfile: .devcontainer/container/Dockerfile.dev
      args:
        BUILDKIT_INLINE_CACHE: ${BUILD_BUILDKIT_INLINE_CACHE:-1}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.12}
        PYTHONDONTWRITEBYTECODE: ${PYTHON_DONT_WRITE_BYTECODE:-1}
        PYTHONUNBUFFERED: ${PYTHON_UNBUFFERED:-1}
        CCACHE_DIR: ${CCACHE_DIR_ABSOLUTE:-/.ccache}
      cache_from:
        - python-slim-dev:latest
    depends_on:
      - python-builder
    env_file:
      - ../../.env
    volumes:
      - ../../:/${WORKSPACE_FOLDER:-workspace}/${PROJECT_NAME:-python-slim}:cached
      - python-ccache-volume:${CCACHE_DIR_ABSOLUTE:-/.ccache}
      - python-pip-cache:/root/.cache/pip
      - python-pycache-volume:/${WORKSPACE_FOLDER:-workspace}/.pycache
    command: ["sleep", "infinity"]
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    runtime: ${NVIDIA_RUNTIME:-runc}
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics
      NVIDIA_REQUIRE_CUDA: "cuda>=11.0"
      COMPOSE_PROJECT_NAME: ${PYTHON_PROJECT_NAME:-python-slim-dev}
      WORKSPACE_FOLDER: ${WORKSPACE_FOLDER:-workspace}
      PROJECT_NAME: ${PROJECT_NAME:-python-slim}
      PYTHONPATH: "/${WORKSPACE_FOLDER:-workspace}/${PROJECT_NAME:-python-slim}"
      PYTHONFAULTHANDLER: "1"
      PYTHONUNBUFFERED: "1"
      PYTHONOPTIMIZE: "2"
      PYTHONHASHSEED: "random"
      PYTHONPYCACHEPREFIX: "/workspace/.pycache"
      # Performance environment variables
      NUMBA_NUM_THREADS: ${HOST_CPUS:-4}
      OPENBLAS_NUM_THREADS: ${HOST_CPUS:-4}
      MKL_NUM_THREADS: ${HOST_CPUS:-4}
      OMP_NUM_THREADS: ${HOST_CPUS:-4}
    ports:
      - "8888:8888"
      - "5678:5678"
      - "6006:6006"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8888/api/status",
          "||",
          "exit",
          "0",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  python-runtime:
    image: python-slim-runtime:latest
    build:
      context: ../..
      dockerfile: .devcontainer/container/Dockerfile.runtime
      args:
        BUILDKIT_INLINE_CACHE: ${BUILD_BUILDKIT_INLINE_CACHE:-1}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.12}
    depends_on:
      - python-builder

volumes:
  python-ccache-volume:
  python-pip-cache:
  python-pycache-volume:
