name: Python CI

on:
  push:
    branches: [main]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.pre-commit-config.yaml'
  pull_request:
    branches: [main]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.pre-commit-config.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    
    - name: Set up Python
      uses: actions/setup-python@v5.5.0
      with:
        python-version: "3.13.2"  # Hardcoded for CI reliability
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    
    - name: Lint
      run: |
        poetry run black --check .
        poetry run ruff check .
    
    - name: Test
      run: |
        poetry run pytest