name: Python CI

on:
  push:
    branches: [main]
    paths:
      - '**.py'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - '.pre-commit-config.yaml'
  pull_request:
    branches: [main]
    paths:
      - '**.py'
      - 'requirements*.txt'
      - 'pyproject.toml'
      - '.pre-commit-config.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    
    - name: Set up Python
      uses: actions/setup-python@v5.5.0
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4.2.2
    
    - name: Set up Python
      uses: actions/setup-python@v5.5.0
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov
    
    - name: Run tests with coverage
      run: pytest --cov=./ --cov-report=xml
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v5.4.0
      with:
        file: ./coverage.xml
        fail_ci_if_error: false